version: "3"

services:
  marungusunbird:
    build: .
    ports:
      - "8000:8000"
    environment:
      HOST: 127.0.0.1
      PORT: 10011
      USER: serveradmin
      PASS: password
      VSID: 1
      BIND_ADDR: 0.0.0.0
      BIND_PORT: 8000
